# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4aa066726e4797af811a0b9f7cd818444286fc3abfc3e7d24a65a2703ecceb8350075f301aa4f4a6f7740e8672dcfb83d98bab90ab62aabf5e8084e206f18a54

test:
  secret_key_base: f6d4c97dd993d398944cd6ad5a0f8941055eaae468a488a9a6f899f2944541fb7add7333df1a74724ad7bd20472cde97e84b80230ee4ea51235c3e23faf0a66d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
